# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_group', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u7ec4')),
                ('hosts', models.CharField(max_length=128, verbose_name='\u9879\u76ee\u7ec4\u4e3b\u673a')),
                ('creater', models.CharField(max_length=16, verbose_name='\u9879\u76ee\u7ec4\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'back_group',
                'verbose_name': '\u540e\u7aef\u9879\u76ee\u7ec4',
                'verbose_name_plural': '\u540e\u7aef\u9879\u76ee\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='BackProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('creater', models.CharField(max_length=16, verbose_name='\u9879\u76ee\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'back_project',
                'verbose_name': '\u540e\u7aef\u9879\u76ee',
                'verbose_name_plural': '\u540e\u7aef\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='BackTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('project_version', models.IntegerField(verbose_name='\u9879\u76ee\u6784\u5efa\u53f7')),
                ('project_md5', models.CharField(max_length=64, verbose_name='\u9879\u76eemd5\u503c')),
                ('creater', models.CharField(max_length=16, verbose_name='\u4efb\u52a1\u521b\u5efa\u4eba')),
                ('operator', models.CharField(max_length=16, verbose_name='\u4efb\u52a1\u64cd\u4f5c\u4eba')),
                ('cc', models.CharField(default='', max_length=64, verbose_name='\u4efb\u52a1\u6284\u9001\u4eba')),
                ('complete_status', models.CharField(max_length=32, verbose_name='\u5b8c\u6210\u72b6\u6001')),
                ('review_status', models.CharField(max_length=32, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('reviewer', models.CharField(default='', max_length=32, verbose_name='\u5ba1\u6838\u4eba')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='\u4efb\u52a1\u9644\u4ef6')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('back_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.BackGroup')),
                ('back_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.BackProject')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'back_task',
                'verbose_name': '\u540e\u7aef\u4efb\u52a1',
                'verbose_name_plural': '\u540e\u7aef\u4efb\u52a1',
                'permissions': (('check_back_tasks', 'Can check all back tasks'),),
            },
        ),
        migrations.CreateModel(
            name='FrontHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_host', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u4e3b\u673a')),
                ('creater', models.CharField(default='', max_length=16, verbose_name='\u9879\u76ee\u4e3b\u673a\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'front_host',
                'verbose_name': '\u524d\u7aef\u9879\u76ee\u4e3b\u673a',
                'verbose_name_plural': '\u524d\u7aef\u9879\u76ee\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='FrontProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('creater', models.CharField(default='', max_length=16, verbose_name='\u9879\u76ee\u7ec4\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('front_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.FrontHost')),
            ],
            options={
                'db_table': 'front_project',
                'verbose_name': '\u524d\u7aef\u9879\u76ee',
                'verbose_name_plural': '\u524d\u7aef\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='FrontTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('project_version', models.IntegerField(verbose_name='\u9879\u76ee\u6784\u5efa\u53f7')),
                ('project_md5', models.CharField(max_length=64, verbose_name='\u9879\u76eemd5\u503c')),
                ('creater', models.CharField(max_length=16, verbose_name='\u4efb\u52a1\u521b\u5efa\u4eba')),
                ('operator', models.CharField(max_length=16, verbose_name='\u4efb\u52a1\u64cd\u4f5c\u4eba')),
                ('cc', models.CharField(default='', max_length=64, verbose_name='\u4efb\u52a1\u6284\u9001\u4eba')),
                ('complete_status', models.CharField(max_length=32, verbose_name='\u5b8c\u6210\u72b6\u6001')),
                ('review_status', models.CharField(max_length=32, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('reviewer', models.CharField(default='', max_length=32, verbose_name='\u5ba1\u6838\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('front_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.FrontHost')),
                ('front_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.FrontProject')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'front_task',
                'verbose_name': '\u524d\u7aef\u4efb\u52a1',
                'verbose_name_plural': '\u524d\u7aef\u4efb\u52a1',
                'permissions': (('check_front_tasks', 'Can check all front tasks'),),
            },
        ),
        migrations.CreateModel(
            name='FrontType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('creater', models.CharField(default='', max_length=16, verbose_name='\u9879\u76ee\u7c7b\u578b\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'front_type',
                'verbose_name': '\u524d\u7aef\u9879\u76ee\u7c7b\u578b',
                'verbose_name_plural': '\u524d\u7aef\u9879\u76ee\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='fronttask',
            name='front_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.FrontType'),
        ),
        migrations.AddField(
            model_name='frontproject',
            name='front_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.FrontType'),
        ),
        migrations.AddField(
            model_name='backgroup',
            name='back_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.BackProject'),
        ),
    ]
