# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_image',
            field=models.ImageField(default='image/default.png', upload_to='image/', verbose_name='\u5934\u50cf'),
        ),
    ]
